version: "3.9"

services:
  app:
    build: .
    container_name: claim-submission
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./template-mapping.json:/app/template-mapping.json:ro
